package carrerahilos;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
public class PistaCarreras extends javax.swing.JFrame {

//    int miliseg = 0;
//    int seg = 0;
//    int min = 0;
//    int hora = 0;
//    boolean estado;

    /**
     * Creates new form PistaCarreras
     */
    public PistaCarreras() {
        initComponents();
        setLocationRelativeTo(null);
        txtTiempo.setEnabled(false);
    }

    public JButton getBtnIniciar() {
        return btnIniciar;
    }

    public void setBtnIniciar(JButton btnIniciar) {
        this.btnIniciar = btnIniciar;
    }

    public JLabel getPrimerAuto() {
        return lblCarro1;
    }

    public JLabel getSegundoAuto() {
        return lblCarro2;
    }

    public JLabel getTercerAuto() {
        return lblCarro3;
    }

    public JLabel getMeta() {
        return lblMeta;
    }

    public JTextField getTxtTiempo() {
        return txtTiempo;
    }

    public void setTxtTiempo(JTextField txtTiempo) {
        this.txtTiempo = txtTiempo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCarro1 = new javax.swing.JLabel();
        lblCarro2 = new javax.swing.JLabel();
        lblCarro3 = new javax.swing.JLabel();
        lblMeta = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtTiempo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-coche-de-carreras-48.png"))); // NOI18N
        jPanel1.add(lblCarro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, 50));

        lblCarro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-coche-de-carreras-48 (1).png"))); // NOI18N
        jPanel1.add(lblCarro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 50));

        lblCarro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-coche-de-carreras-48 (2).png"))); // NOI18N
        jPanel1.add(lblCarro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, 20));

        lblMeta.setBackground(new java.awt.Color(255, 204, 0));
        lblMeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel1.add(lblMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 40, 290));

        lblPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PISTA1.jpg"))); // NOI18N
        jPanel1.add(lblPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 590, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 780, 330));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Pista de Carrera");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        btnIniciar.setBackground(new java.awt.Color(153, 153, 153));
        btnIniciar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 130, 40));

        btnSalir.setBackground(new java.awt.Color(153, 153, 153));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setText("Salir ");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 80, 30));
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tiempo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void cronometro(){
//      estado = true;
//        
//        Thread hilo = new Thread() {
//        public void run() {
//            for (;;) {
//                if (estado == true) {
//                    try {
//                        sleep(1);
//                        if (miliseg >= 1000) {
//                            miliseg = 0;
//                            seg++;
//                        }
//                        
//                        if (seg >= 60) {
//                            miliseg = 0;
//                            seg = 0;
//                            min++;
//                        }
//                        
//                        if (min >= 60) {
//                            miliseg = 0;
//                            seg = 0;
//                            min = 0;
//                            hora++;
//                        }
//
//                        lblCrono.setText(hora + " : " + min + " : " + seg + " : ");
//                        lblMilisec.setText(" " + miliseg);
//                        miliseg++;
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(null, e.getMessage());
//                    }
//                } else {
//                    break;
//                }
//            }
//        }
//    };
//        hilo.start();  
//    }
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        lblCarro1.setLocation(0, lblCarro1.getLocation().y);
        lblCarro2.setLocation(0, lblCarro2.getLocation().y);
        lblCarro3.setLocation(0, lblCarro3.getLocation().y);

        ProcesoCarritos ca1 = new ProcesoCarritos(lblCarro1, this);
        ProcesoCarritos ca2 = new ProcesoCarritos(lblCarro2, this);
        ProcesoCarritos ca3 = new ProcesoCarritos(lblCarro3, this);

        ca1.start();
        ca2.start();
        ca3.start();
    }//GEN-LAST:event_btnIniciarMouseClicked

            /**
             * @param args the command line arguments
             */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PistaCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PistaCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PistaCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PistaCarreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PistaCarreras().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarro1;
    private javax.swing.JLabel lblCarro2;
    private javax.swing.JLabel lblCarro3;
    private javax.swing.JLabel lblMeta;
    private javax.swing.JLabel lblPista;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables

            public JButton getjButton1() {
                return btnIniciar;
            }

            public JPanel getjPanel1() {
                return jPanel1;
            }

            public JLabel getLblCarro1() {
                return lblCarro1;
            }

            public JLabel getLblCarro2() {
                return lblCarro2;
            }

            public JLabel getLblCarro3() {
                return lblCarro3;
            }

            public JLabel getLblPista() {
                return lblPista;
            }

            public JLabel getLblMeta() {
                return lblMeta;
            }
        }
